# homework1
# 數字變數
number = 10

# 字串變數
string = "Hello, World!"


# 宣告 List
fruits = ["apple", "banana", "cherry"]

# 添加元素
fruits.append("orange")  # List 現在為 ["apple", "banana", "cherry", "orange"]

# 查詢元素
print(fruits[1])  # 輸出 "banana"

# 更新元素
fruits[1] = "blueberry"  # List 現在為 ["apple", "blueberry", "cherry", "orange"]

# 刪除元素
fruits.remove("cherry")  # List 現在為 ["apple", "blueberry", "orange"]


# 宣告 Dict
person = {"name": "John", "age": 30}

# 添加元素
person["city"] = "New York"  # Dict 現在為 {"name": "John", "age": 30, "city": "New York"}

# 查詢元素
print(person["name"])  # 輸出 "John"

# 更新元素
person["age"] = 31  # Dict 現在為 {"name": "John", "age": 31, "city": "New York"}

# 刪除元素
del person["city"]  # Dict 現在為 {"name": "John", "age": 31}


# 宣告 List
numbers = [1, 2, 3, 4, 5]

# 用 for loop 操作 List
for num in numbers:
    print(num)


# 宣告 List
numbers = [1, 2, 3, 4, 5]

# 用 for loop 搭配 if else 判斷元素
for num in numbers:
    if num % 2 == 0:
        print(f"{num} 是偶數")
    else:
        print(f"{num} 是奇數")


def greet():
    print("Hello, World!")


def greet_person(name):
    print(f"Hello, {name}!")


def get_five():
    return 5


def add(a, b):
    return a + b
